import type {NextPage} from 'next'
import Head from 'next/head'
import {useInfiniteQuery} from "react-query";
import {listArticles} from "../services/article";
import classNames from "classnames";
import {useEffect, useRef} from "react";
import Link from 'next/link';

const Home: NextPage = () => {
    const loadingRef = useRef<HTMLDivElement>(null)
    const Observer = useRef<IntersectionObserver>()
    const {
        data: articles,
        fetchNextPage,
        hasNextPage,
        isFetchingNextPage,
    } = useInfiniteQuery(['articles'], listArticles, {
        getNextPageParam: (lastPage, pages) => {
            return {current: lastPage.data.current + 1}
        },
    });
    useEffect(() => {
        Observer.current = new IntersectionObserver(function (entries) {
            entries.forEach((entry) => {
                if (entry.isIntersecting) {
                    fetchNextPage()
                }
            })
        })
        if (loadingRef.current) {
            Observer.current.observe(loadingRef.current)
        }
    }, [fetchNextPage])
    return (
        <>
            <Head>
                <title>互联网技术周报</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={classNames('divide-y', 'max-w-xl', 'mx-auto')}>
                {articles?.pages.map(item => item.data.records) && articles?.pages.map(item => item.data.records).flat().map(article => (
                    <div className={classNames('py-6')} key={article.id}>
                        <header className={classNames('text-left')}>{article.createTime}</header>
                        <Link href={`https://zzfzzf.com/article/${article.id}`}>
                            <a target={'_blank'} className={classNames('text-2xl', 'font-bold','text-center')}>{article.title}</a>
                        </Link>
                    </div>
                ))}
            </div>
            <div className={'text-center'} ref={loadingRef}>
                {isFetchingNextPage
                    ? 'Loading more...'
                    : hasNextPage
                        ? 'Load More'
                        : 'Nothing more to load'}
            </div>
        </>
    )
}

export default Home
