import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import classNames from "classnames";

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>ByteCache</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={classNames('max-w-screen-md', 'md:max-w-screen-xl', 'mx-auto')}>
                <h1 className={classNames('text-brand1')}>
                    ByteCache.
                </h1>
                <div>
                    <main>
                        LATEST TUTORIALS
                    </main>
                    <aside>
                        1
                    </aside>
                </div>
            </main>

            <footer className={classNames('max-w-screen-md', 'md:max-w-screen-xl', 'mx-auto','text-center')}>
                <a
                    href="https://github.com/bytecache"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by ByteCache
                </a>
            </footer>
        </div>
    )
}

export default Home
